static_resources:
  listeners:
  - name: spicedb-pgdb-listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 50052
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: spicedb-pgdb-tcp
          cluster: spicedb-pgdb-cluster

  clusters:
  - name: spicedb-pgdb-cluster
    type: STRICT_DNS
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: spicedb-pgdb-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: spicedb-pgdb
                port_value: 50051
    dns_refresh_rate: 5s
    dns_lookup_family: V4_ONLY
