static_resources:
  listeners:
  - name: spicedb-crdb-listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 50051
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: spicedb-crdb-tcp
          cluster: spicedb-crdb-cluster

  clusters:
  - name: spicedb-crdb-cluster
    type: STRICT_DNS
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: spicedb-crdb-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: spicedb-crdb
                port_value: 50051
    dns_refresh_rate: 5s
    dns_lookup_family: V4_ONLY
